---

- name: First Playbook
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create log file
      file:
        path: /tmp/testlogfile.log
        state: touch
        #mode: "u+rw,g-wx,o-rwx"
      delegate_to: 127.0.0.1
    - name: Delete log file
      file:
        path: /tmp/testlogfile.log
        state: absent
        #mode: "u+rw,g-wx,o-rwx"
      delegate_to: 127.0.0.1